/*eslint-disable*/

//               num    name                keyword                 is_ariphmetic
OPERATION_HANDLE(0,     SUM,                L"плюс_вайбик"          , true          )
OPERATION_HANDLE(1,     SUB,                L"минус_вайбик"         , true          )
OPERATION_HANDLE(2,     MUL,                L"звёздочка"            , true          )
OPERATION_HANDLE(3,     DIV,                L"очень_минусик"        , true          )
OPERATION_HANDLE(4,     POW,                L"очень_звёздочка"      , true          )
OPERATION_HANDLE(5,     LBRAKET,            L":-)"                  , false         )
OPERATION_HANDLE(6,     RBRAKET,            L";-)"                  , false         )
OPERATION_HANDLE(7,     PLEASE,             L"пж-пж"                , false         )
OPERATION_HANDLE(8,     ASSIGNMENT,         L"всего_за"             , false         )
OPERATION_HANDLE(9,     DECL_ASSIGNMENT,    L"всего_за"             , false         )       
OPERATION_HANDLE(10,    DECL_FLAG,          L"купи"                 , false         )
OPERATION_HANDLE(11,    IF,                 L"сосать?"              , false         ) //NOTE - before1
OPERATION_HANDLE(12,    LBODY,              L"сосать"               , false         ) //NOTE - after1
OPERATION_HANDLE(13,    RBODY,              L"кончать"              , false         )
OPERATION_HANDLE(14,    COND_LBRAKET,       L"туть"                 , false         )
OPERATION_HANDLE(15,    COND_RBRAKET,       L"и_туть"               , false         )
OPERATION_HANDLE(16,    WHILE,              L"много_сосать?"        , false         )
OPERATION_HANDLE(17,    POW_ASSIGNMENT,     L"подороже_что_пиздец"  , false         ) //NOTE - before2
OPERATION_HANDLE(18,    SUM_ASSIGNMENT,     L"подороже"             , false         ) //NOTE - after2
OPERATION_HANDLE(19,    SUB_ASSIGNMENT,     L"подешевле"            , false         )
OPERATION_HANDLE(20,    MUL_ASSIGNMENT,     L"очень_подороже"       , false         )
OPERATION_HANDLE(21,    DIV_ASSIGNMENT,     L"очень_подешевле"      , false         )
OPERATION_HANDLE(22,    EQ,                 L"близняшки"            , true          )
OPERATION_HANDLE(23,    NEQ,                L"какашки"              , true          )
OPERATION_HANDLE(24,    LESS,               L"тут_дороже:--"        , true          )
OPERATION_HANDLE(25,    LESSEQ,             L"тут_мб_дороже:--"     , true          )
OPERATION_HANDLE(26,    GREAT,              L"--:тут_дороже"        , true          )
OPERATION_HANDLE(27,    GREATEQ,            L"--:тут_мб_дороже"     , true          )
OPERATION_HANDLE(28,    ELSE,               L"не_сосать?"           , false         )
OPERATION_HANDLE(29,    FUNC,               L"алё"                  , false         )
OPERATION_HANDLE(30,    FUNC_LBRAKET,       L":-)"                  , false         )
OPERATION_HANDLE(31,    FUNC_RBRAKET,       L";-)"                  , false         )
OPERATION_HANDLE(32,    MAIN,               L"привет_масик"         , false         )
OPERATION_HANDLE(33,    ARGS_COMMA,         L"ещё"                  , false         )
OPERATION_HANDLE(34,    CALL_FUNC_LBRAKET,  L":-)"                  , false         )
OPERATION_HANDLE(35,    CALL_FUNC_RBRAKET,  L";-)"                  , false         )
OPERATION_HANDLE(36,    RET,                L"кладу_трубочку"       , false         )