/*eslint-disable*/

//               num    name                keyword           count_op
OPERATION_HANDLE(0,     SUM,                L"плюсик"               )
OPERATION_HANDLE(1,     SUB,                L"минусик"              )
OPERATION_HANDLE(2,     MUL,                L"звёздочка"            )
OPERATION_HANDLE(3,     DIV,                L"очень_минусик"        )
OPERATION_HANDLE(4,     POW,                L"очень_звёздочка"      )
OPERATION_HANDLE(5,     LBRAKET,            L":-)"                  )
OPERATION_HANDLE(6,     RBRAKET,            L";-)"                  )
OPERATION_HANDLE(7,     PLEASE,             L"пж-пж"                )
OPERATION_HANDLE(8,     ASSIGNMENT,         L"всего_за"             )
OPERATION_HANDLE(9,     DECL_ASSIGNMENT,    L"всего_за"             )       
OPERATION_HANDLE(10,    DECL_FLAG,          L"купи"                 )
OPERATION_HANDLE(11,    IF,                 L"сосать?"              ) //NOTE - before1
OPERATION_HANDLE(12,    LBODY,              L"сосать"               ) //NOTE - after1
OPERATION_HANDLE(13,    RBODY,              L"кончать"              )
OPERATION_HANDLE(14,    COND_LBRAKET,       L"туть"                 )
OPERATION_HANDLE(15,    COND_RBRAKET,       L"и_туть"               )
OPERATION_HANDLE(16,    WHILE,              L"много_сосать?"        )
OPERATION_HANDLE(17,    POW_ASSIGNMENT,     L"подороже_что_пиздец"  ) //NOTE - before2
OPERATION_HANDLE(18,    SUM_ASSIGNMENT,     L"подороже"             ) //NOTE - after2
OPERATION_HANDLE(19,    SUB_ASSIGNMENT,     L"подешевле"            )
OPERATION_HANDLE(20,    MUL_ASSIGNMENT,     L"очень_подороже"       )
OPERATION_HANDLE(21,    DIV_ASSIGNMENT,     L"очень_подешевле"      )
OPERATION_HANDLE(22,    EQ,                 L"близняшки"            )
OPERATION_HANDLE(23,    NEQ,                L"какашки"              )
OPERATION_HANDLE(24,    LESS,               L"тут_дороже:--"        )
OPERATION_HANDLE(25,    LESSEQ,             L"тут_мб_дороже:--"     )
OPERATION_HANDLE(26,    GREAT,              L"--:тут_дороже"        )
OPERATION_HANDLE(27,    GREATEQ,            L"--:тут_мб_дороже"     )
OPERATION_HANDLE(28,    ELSE,               L"не_сосать?"           )
OPERATION_HANDLE(29,    FUNC,               L"aлё"                  )
OPERATION_HANDLE(30,    FUNC_LBRAKET,       L":-)"                  )
OPERATION_HANDLE(31,    FUNC_RBRAKET,       L";-)"                  )
OPERATION_HANDLE(32,    MAIN,               L"привет_масик"         )
OPERATION_HANDLE(33,    ARGS_COMMA,         L"ещё"                  )
OPERATION_HANDLE(34,    CALL_FUNC_LBRAKET,  L":-)"                  )
OPERATION_HANDLE(35,    CALL_FUNC_RBRAKET,  L";-)"                  )
OPERATION_HANDLE(36,    RET,                L"кладу_трубочку"       )