<start> ::= (<statement>)+ <END>

<statement> ::= <if> | <while> | ((<declaration> | <expr>)? ("пж-пж")+)

<expr> ::= <assignment>
<assignment> ::= <sum> ( "всего_за" <assignment> )*
<sum> ::= <mul> (("плюсик" | "минусик") <mul>)*
<mul> ::= <pow> (("звёздочка" | "очень_минусик") <pow>)*
<pow> ::= <brakets> ("очень_звёздочка" <pow>)*
<brakets> ::= ":-)" <expr> ";-)" | <varnum>
<varnum> ::= <NUM> | <NAME>

<declaration> ::= "купи" <NAME> ("всего_за" <expr>)?

<if> ::= "сосать?" <condition> <body>
<while> ::= "много_сосать?" <condition> <body>

<condition> ::= "туть" <expr> "и_туть"
<body> ::= "сосать" (<statement>)* "кончать"

