<start> ::= <sum> <END>
<sum> ::= <mul> (("плюсик" | "минусик") <mul>)*
<mul> ::= <pow> (("звёздочка" | "очень_минусик") <pow>)*
<pow> ::= <brakets> ("очень_звёздочка" <pow>)*
<brakets> ::= ":-)" <sum> ";-)" | <NUM>